  groups:
  - name: site_availability.rules
    rules:
    - alert: SiteDown
      expr: |
        probe_success == 0 and up == 1        
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Site Down - {{ $labels.instance }} (Job: {{ $labels.job }})"
        description: "Site {{ $labels.instance }} has been down for more than 2 minutes"
