groups:
  - name: InstanceDown
    rules:
      - alert: InstanceDownAlert
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance is Down"
