apiVersion: v1
kind: Service
metadata:
  name: blackbox-exporter
  namespace: monitoring
spec:
  type: NodePort
  selector:
    app: blackbox-exporter
  ports:
  - port: 9115
    targetPort: 9115
    nodePort: 30115
